[package]
name = "bpe-test"
version = "0.3.0-dev" # managed by updgitver
edition = "2021"
authors = ["Guo Zheyong <guozheyong@erayt.com>"]
exclude = ["tests", "test_data", "benches", "examples", ".vscode"]
homepage = ""
repository = ""
license = "Apache-2.0"
readme = "README.md"
description = ""
categories = [""]
documentation = ""
keywords = [""]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [[bench]]
# name = "benchmarks"
# harness = false

[dependencies]
bpe = { path = "../bpe-core" }
log = "0.4.17"
core_affinity = "0.8.1"

[dev-dependencies]
