from typing import Any

def start() -> bool: ...
def stop() -> bool: ...
def def_incoming(name: str, names: list, types: list, lengths: list) -> int: ...
def def_stream(name: str, names: list, types: list, lengths: list) -> int: ...
def new_data(record_id: int, bdata: bytes) -> bool: ...
def def_mapper(sql: str, callback: Any) -> int: ...
def def_mapper_bind_aggregate(sql: str, aggregate_id: int) -> int: ...
def def_aggregate(sql: str, callback: Any) -> int: ...
