[package]
name = "shower4py"
version = "0.1.0"
edition = "2021"
authors = ["Guo Zheyong <guozheyong@erayt.com>"]
exclude = ["tests", "test_data", "benches", "examples", ".vscode"]
homepage = ""
repository = ""
license = "Apache-2.0"
readme = "README.md"
description = ""
categories = [""]
documentation = ""
keywords = [""]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
shower = { path = "../shower-core" }
pyo3 = "0.20.0"
log = "0.4.17"

[dev-dependencies]
